"""Initial migration.

Revision ID: 261a0d71f7ee
Revises: 
Create Date: 2024-10-23 10:40:42.180226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261a0d71f7ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_excel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=255), nullable=True),
    sa.Column('idcard', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ocr_area', sa.String(length=255), nullable=True),
    sa.Column('ocr_province', sa.String(length=255), nullable=True),
    sa.Column('ocr_city', sa.String(length=255), nullable=True),
    sa.Column('overdue_day', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('gps', sa.String(length=500), nullable=True),
    sa.Column('due_date', sa.String(length=255), nullable=True),
    sa.Column('application_amount', sa.Float(), nullable=True),
    sa.Column('contactable', sa.String(length=255), nullable=True),
    sa.Column('mission_id', sa.String(length=255), nullable=True),
    sa.Column('emergs_name0', sa.String(length=255), nullable=True),
    sa.Column('emergs_phone0', sa.String(length=255), nullable=True),
    sa.Column('emergs_relation0', sa.String(length=255), nullable=True),
    sa.Column('emergs_name1', sa.String(length=255), nullable=True),
    sa.Column('emergs_phone1', sa.String(length=255), nullable=True),
    sa.Column('emergs_relation1', sa.String(length=255), nullable=True),
    sa.Column('face_photo_url', sa.String(length=255), nullable=True),
    sa.Column('outstanding', sa.Float(), nullable=True),
    sa.Column('repay_principal_amt', sa.Float(), nullable=True),
    sa.Column('nama_user', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('gambar', sa.String(length=255), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('tanggal_perubahan', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_excel')
    # ### end Alembic commands ###
